# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d773aa7513bdc72c1ee03c2c144b2452a33713a901ed5cd6826f346a01a30205a8f561681cb236a51f42b5ebfb1713df98445d47d0877f9bf34c9e5961d456c
  twitter_key: clUZzZpmQQPSH4MyoCBSzJLeb
  twitter_secret: 9vLMcgmqVVfpRVGnsq7KaOe7UlIBC79EWcf0ppXFZhsLe75Bzt
  google_client_id: 620327734934.apps.googleusercontent.com
  google_client_secret: R801R7QaSCbFYr2xIAZxfLsr


test:
  secret_key_base: 651bb2b2862bd295679b0e328012eb623fd8f74e95ce7f73e2076a88423a512bc631f696f582e44c7bfb4a1d132146fd53dd84f4664023f6532c745708095a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  google_consumer_key: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_consumer_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  
